const newsDataA = [
    {   
        id:1,
        theme: "INSPIRATION",
        title: "4 Natural Ways To Have Young Skin",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name:"Benjamin Miller",
        date:"December 28, 2017",
        image:'/images/lifestyle.png',
        author:'images/author3.png',
    },
    {   
        id:2,
        theme:"LIFESTYLE",
        title: "4 Natural Ways To Have Young Skin",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "James Leman",
        date: "April 28, 2016",
        image:'images/Layer 47.png',
        author:'images/author.png',
    },
    {   
        id:3,
        theme:"LIFESTYLE",
        title: "4 Natural Ways To Have Young Skin",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name:"Benjamin Miller",
        date:"October 6, 2016",
        image:'images/Layer 48.png',
        author:'images/author3.png',
    },
    {   
        id:4,
        theme:"INSPIRATION",
        title: "4 Natural Ways To Have Young Skin",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name:"Benjamin Miller",
        date:"October 6, 2016",
        image:'images/Layer 48.png',
        author:'images/author3.png',
    },
    {   
        id:5,
        theme:"TRIP",
        title: "4 Natural Ways To Have Young Skin",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name:"Benjamin Miller",
        date:"October 6, 2016",
        image:'images/countriestrip.png',
        author:'images/author3.png',
    },
    {   
        id:6,
        theme:"PHOTOGRAPHY",
        title: "4 Natural Ways To Have Young Skin",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name:"Benjamin Miller",
        date:"October 6, 2016",
        image:'images/road.png',
        author:'images/author3.png',
    },
    {   
        id:7,
        theme:"PHOTOGRAPHY",
        title: "4 Natural Ways To Have Young Skin",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name:"Benjamin Miller",
        date:"October 6, 2016",
        image:'images/street.png',
        author:'images/author3.png',
    }
]

export default newsDataA