const newsDataС = [
    {
        id: 1,
        theme: "INSPIRATION",
        title: "Food That Actually Taste Better When You Freeze",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "Benjamin Miller",
        date: "December 28, 2017",
        image: '/images/Layer3.png',
        author: 'images/author3.png',
    },
    {
        id: 2,
        theme: "TRIP",
        title: "Why It’s Amazing To Date People Who Love Traveling",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "Benjamin Miller",
        date: "April 28, 2016",
        image: 'images/Layer4.png',
        author: 'images/author3.png',
    },
    {
        id: 3,
        theme: "LIFESTYLE",
        title: "5 Useful Tips for Novice Painters",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "Benjamin Miller",
        date: "October 6, 2016",
        image: 'images/lifestyleheet.png',
        author: 'images/author3.png',
    }
    ,
    {
        id: 4,
        theme: "TRIP",
        title: "Why It’s Amazing To Date People Who Love Traveling",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "Benjamin Miller",
        date: "April 28, 2016",
        image: 'images/Layer4.png',
        author: 'images/author3.png',
    },
    {
        id: 5,
        theme: "LIFESTYLE",
        title: "5 Useful Tips for Novice Painters",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "Benjamin Miller",
        date: "October 6, 2016",
        image: 'images/Layer5.png',
        author: 'images/author3.png',
    },
    {
        id: 6,
        theme: "INSPIRATION",
        title: "Food That Actually Taste Better When You Freeze",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "Benjamin Miller",
        date: "December 28, 2017",
        image: '/images/ccelebri.png',
        author: 'images/author3.png',
    },
    {
        id: 7,
        theme: "PHOTOGRAPHY",
        title: "Food That Actually Taste Better When You Freeze",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "Benjamin Miller",
        date: "December 28, 2017",
        image: '/images/skytree.png',
        author: 'images/author3.png',
    },
    {
        id: 8,
        theme: "PHOTOGRAPHY",
        title: "Food That Actually Taste Better When You Freeze",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "Benjamin Miller",
        date: "December 28, 2017",
        image: '/images/face.png',
        author: 'images/author3.png',
    },
    {
        id: 9,
        theme: "PHOTOGRAPHY",
        title: "Food That Actually Taste Better When You Freeze",
        description: " Lorem ipsum dolor sit amet, to consectetur adipi scing elit. Nulla vehicula loremandlacus.Vestibulum vitae mauris lorem ipsum doar.",
        name: "Benjamin Miller",
        date: "December 28, 2017",
        image: '/images/twoface.png',
        author: 'images/author3.png',
    }
]

export default newsDataС